export const FACEBOOK_LOGIN_SUCCESS = 'facebook_login_success'
export const FACEBOOK_LOGIN_FAIL = 'facebook_login_fail'
export const FETCH_JOBS = 'fetch jobs'
export const LIKE_JOBS = 'like jobs'
export const CLEAR_LIKED_JOBS = 'clear liked jobs'